#!/bin/sh -e

case "$1" in
    configure)
        # デスクトップエントリのデータベースを更新
        update-desktop-database
        # アイコンキャッシュを更新
        gtk-update-icon-cache -f /usr/share/icons/hicolor/
    ;;
esac

exit 0